// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDy5YxVeQxS0Or2wnr5EoNxpbXdqmTWcs',
    appId: '1:278126871771:web:ec0586009d89ccbd6678fe',
    messagingSenderId: '278126871771',
    projectId: 'baseleal-9fb49',
    authDomain: 'baseleal-9fb49.firebaseapp.com',
    storageBucket: 'baseleal-9fb49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKZsTKvcUw4ctcIkR0rAH7pwgu87it1dw',
    appId: '1:278126871771:android:bddbe2642b93ae2d6678fe',
    messagingSenderId: '278126871771',
    projectId: 'baseleal-9fb49',
    storageBucket: 'baseleal-9fb49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH1Nlkw1CuEtq_-SVTbeWbcjs8JIjtMJs',
    appId: '1:278126871771:ios:cf16938f072793796678fe',
    messagingSenderId: '278126871771',
    projectId: 'baseleal-9fb49',
    storageBucket: 'baseleal-9fb49.appspot.com',
    iosBundleId: 'com.example.baseleal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH1Nlkw1CuEtq_-SVTbeWbcjs8JIjtMJs',
    appId: '1:278126871771:ios:cf16938f072793796678fe',
    messagingSenderId: '278126871771',
    projectId: 'baseleal-9fb49',
    storageBucket: 'baseleal-9fb49.appspot.com',
    iosBundleId: 'com.example.baseleal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDy5YxVeQxS0Or2wnr5EoNxpbXdqmTWcs',
    appId: '1:278126871771:web:9ad97b00856dc5c46678fe',
    messagingSenderId: '278126871771',
    projectId: 'baseleal-9fb49',
    authDomain: 'baseleal-9fb49.firebaseapp.com',
    storageBucket: 'baseleal-9fb49.appspot.com',
  );
}
